ndarray

In [ ]:
import numpy as np
vector = np.array([1, 2, 3, 4])           # 1D array
matrix = np.array([[1, 2, 3], [4, 5, 6]]) # 2D array

print("Vector:", vector)
print("Matrix:\n", matrix)



Vector: [1 2 3 4]
Matrix:
 [[1 2 3]
 [4 5 6]]


In [ ]:
vector.shape  #row x column

(4,)

In [ ]:
matrix.shape

(2, 3)

In [ ]:
matrix.ndim  #Dimension-1D,2D,3D

2

In [ ]:
vector.ndim

1

In [ ]:
vector.dtype  #datatype of element depends on the system

dtype('int64')

In [ ]:
matrix.size   #total no. of elements

6

Creating Arrays Fast

In [ ]:
import numpy as np
zero=np.zeros((3,3))     #useful for initializing weight matrices
zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
one=np.ones((2,4))      #useful for mask/bias
one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
identity=np.eye(3)   #identity matrix of 3 x 3
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arrange=np.arange(0,12,2)  #like  range in pythoni.e from 0 to 12 and difference is 2
arrange

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
space=np.linspace(0,1,5)   #from 0 to 1 it prints 5 evenly spaced integer
space

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.random.seed(42)  # for reproducibility
random_arr = np.random.rand(2, 3)       # uniform [0, 1)
random_arr


array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452]])

In [ ]:
random_normal = np.random.randn(2, 3)   # standard normal distribution
random_normal

array([[ 1.57921282,  0.76743473, -0.46947439],
       [ 0.54256004, -0.46341769, -0.46572975]])

INDEXING AND SLICING

In [ ]:
#1-D array
data = np.array([10, 20, 30,5, 40, 50, 60])
data[3]                                       #prints element at index 3

np.int64(5)

In [ ]:
data[1:4]             #includes element starting from 1 to 3 excluding 4

array([20, 30,  5])

In [ ]:
data[-2:]             #prints last two elements

array([50, 60])

In [ ]:
#2-D array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix[1,2]        #prints the element at 2nd row 2ndcolumn starting row and column value from 0


np.int64(6)

In [ ]:
matrix[2,:]   #prints the entire row 2

array([7, 8, 9])

In [ ]:
matrix[:,1]   # prints entire column 1

array([2, 5, 8])

In [ ]:
#Boolean Masking
mask=data>30        #prints the boolean true of the element is greater than 30
mask

array([False, False, False, False,  True,  True,  True])

In [ ]:
data[mask]             #prints the filtered element directly

array([40, 50, 60])

In [ ]:
data[data>30]        #prints the entire code wriiten above in single line

array([40, 50, 60])

In [ ]:
arr=np.arange(12)          #creates 1 D array of 12 elements
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr.shape         #prints the dimension of array

(12,)

In [ ]:
reshaped=arr.reshape(3,4)       #reshapes into the matrix with 3 rows and 4 columns
reshaped 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
reshaped_again=arr.reshape(2,2,3)          #prints 2 blocks of 2 x 3 matrix
reshaped_again

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [ ]:
flattened=reshaped.flatten()            #flattened back to 1-D
flattened

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
auto_reshape=arr.reshape(4,-1)        #auto calculates the columns i.e. 3 to make 4x3=12 the size of elements
auto_reshape

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

BROADCASTING:NumPy automatically expands the smaller arrays to match the larger ones when possible

In [ ]:
#Scalar broadcasting
arr=np.array([1,2,3])           # broadcast to every elements
arr+10

array([11, 12, 13])

In [ ]:
#Vector Broadcasting
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])    #i.e. broadcast across row/columns depending on shape
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
row_vector=np.array([10,20,30])    #row_vector is broadcasted across each row of matrix
matrix+row_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

VECTORIZED MATH AND LINEAR ALGEBRA BASICS

In [ ]:
data=np.array([[1,2,3],[4,5,6]])
data.sum()

np.int64(21)

In [ ]:
data.sum(axis=0)           #sum along columns

array([5, 7, 9])

In [ ]:
data.sum(axis=1)      #sum along rows

array([ 6, 15])

In [ ]:
data.mean()            #mean

np.float64(3.5)

In [ ]:
data.std()            #standard deviation

In [ ]:
#DOT PRODUCT 
a=np.array([1,2,3])
b=np.array([4,5,6])
np.dot(a,b)

np.int64(32)

In [ ]:
#MATRIX MULTIPLICATION
inputs=np.array([[1,2],[3,4]])
weights = np.array([[0.5, 0.1], [0.2, 0.3]]) 
output = inputs @ weights 
output


array([[0.9, 0.7],
       [2.3, 1.5]])

LIVE DEMO:NORMALIZING A DATASET

In [ ]:
dataset = np.array([
    [170, 65, 25],
    [160, 55, 30],
    [180, 80, 22],
    [175, 70, 28],
    [165, 60, 35]],dtype=float)
dataset


array([[170.,  65.,  25.],
       [160.,  55.,  30.],
       [180.,  80.,  22.],
       [175.,  70.,  28.],
       [165.,  60.,  35.]])

In [ ]:
column_means = dataset.mean(axis=0)
column_means

array([170.,  66.,  28.])

In [ ]:
column_stds = dataset.std(axis=0)
column_stds

array([7.07106781, 8.60232527, 4.42718872])

In [ ]:
# Broadcasting does all the work here - no loop needed!
standardized = (dataset - column_means) / column_stds
standardized

array([[ 0.        , -0.11624764, -0.67763093],
       [-1.41421356, -1.27872403,  0.45175395],
       [ 1.41421356,  1.62746694, -1.35526185],
       [ 0.70710678,  0.46499055,  0.        ],
       [-0.70710678, -0.69748583,  1.58113883]])

In [ ]:
standardized.mean(axis=0).round(2)

array([ 0., -0.,  0.])

In [ ]:
standardized.std(axis=0).round(2)

array([1., 1., 1.])